### ISSUE TITLE
how is it different from the standard geometry_msgs?

### ISSUE THREAD

**Issue by MengGuo** [adaldo/geomtwo#1]
also what are the advantages of using them?

**Comment by adaldo** [comment]
Basically, `geometry_msgs` has most messages for 3D space (only Pose2D is for 2D space).
The intent with this package was to define geometry messages for 2D space.
The main advantage would be the Python implementation file, `impl.py`, which allows the user to perform common operations on these types "natively" (i.e., without having to explicitly convert them to `numpy` arrays or similar).

For example:

```
import geomtwo.msg as gms
import geomtwo.impl as gmi

# ros message
vr = gms.Vector(1,2)
# casting to class with methods
vi = gmi.Vector(vr)
# another vector
v2 = gmi.Vector(3,4)
# do stuff
scal_prod = u*v
print(u+v)
# other types
tw = Twist(v2, 0.3)
# Rodriguez formula maps twists into transforms
trs = tw.integrate(tw, 1.0)
```

Potential users should be aware that all of it is still very primitive, and I expect that a lot of adjusting will be needed in the next months. Also, at the moment there is no documentation.

**Comment by MengGuo** [comment]
Great! theses clarifications can be in the README.md, I believe.

**Comment by adaldo** [comment]
True :) thanks for the tip!
I will add some usage examples to the readme once the interface has stabilized a bit.
I also have plans to add docstrings so that I can generate a more formal documentation.

**Comment by adaldo** [comment]
I am closing the issue for now.
